export const petDatabase = [
  {
    id: 1,
    name: "Buddy",
    breed: "Golden Retriever",
    species: "Dog",
    location: "Cleveland, OH",
    age: "Adult",
    specialNeeds: false,
    image: "https://placedog.net/300/200?id=1",
    description:
      "Buddy is a loyal and playful Golden Retriever who loves spending time outdoors. He's well-trained and great with children, making him a perfect family dog. Buddy enjoys long walks and playing fetch in the park. He has a friendly demeanor and gets along well with other pets. He is up to date on all vaccinations and is ready to find his forever home.",
  },
  {
    id: 2,
    name: "Mittens",
    breed: "Maine Coon",
    species: "Cat",
    location: "Columbus, OH",
    age: "Young",
    specialNeeds: false,
    image: "https://placekitten.com/300/200?id=1",
    description:
      "Mittens is a beautiful Maine Coon with a luxurious coat and a curious personality. She loves exploring her surroundings and enjoys lounging in sunny spots. Mittens is affectionate and loves gentle head scratches. She’s litter trained and would thrive in a loving home. Her charming personality will win you over instantly.",
  },
  {
    id: 3,
    name: "Charlie",
    breed: "Cockatiel",
    species: "Bird",
    location: "Cincinnati, OH",
    age: "Baby",
    specialNeeds: true,
    image: "https://loremflickr.com/300/200/bird?random=1",
    description:
      "Charlie is a cheerful cockatiel who loves to sing and interact with his surroundings. He thrives on attention and enjoys sitting on your shoulder. Charlie is well-socialized and would do great in a home with plenty of interaction. His vibrant personality will bring joy to your life every day.",
  },
  {
    id: 4,
    name: "Daisy",
    breed: "Beagle",
    species: "Dog",
    location: "Dayton, OH",
    age: "Old",
    specialNeeds: false,
    image: "https://placedog.net/300/200?id=2",
    description:
      "Daisy is a sweet and gentle Beagle with a calm disposition. She enjoys short walks and quiet afternoons. Daisy is great with kids and other pets, making her an ideal companion. She loves belly rubs and snuggling on the couch. Daisy is looking for a loving home where she can relax and be part of the family.",
  },
  {
    id: 5,
    name: "Shadow",
    breed: "Persian",
    species: "Cat",
    location: "Toledo, OH",
    age: "Adult",
    specialNeeds: true,
    image: "https://placekitten.com/300/200?id=2",
    description:
      "Shadow is a gorgeous Persian cat with a calm and regal demeanor. Despite needing some special care, Shadow is affectionate and enjoys being pampered. She prefers quiet environments and is an excellent companion for a relaxed home. Shadow is looking for someone who can provide her the care and love she deserves.",
  },
  {
    id: 6,
    name: "Luna",
    breed: "Siberian Husky",
    species: "Dog",
    location: "Akron, OH",
    age: "Young",
    specialNeeds: false,
    image: "https://placedog.net/300/200?id=3",
    description:
      "Luna is an energetic and intelligent Siberian Husky who loves to explore. She is highly active and would thrive with an adventurous family. Luna enjoys running, hiking, and playing in the snow. Her striking blue eyes and playful nature make her irresistible. She is ready for a home that matches her energy level.",
  },
  {
    id: 7,
    name: "Tiger",
    breed: "Tabby",
    species: "Cat",
    location: "Columbus, OH",
    age: "Baby",
    specialNeeds: false,
    image: "https://placekitten.com/300/200?id=3",
    description:
      "Tiger is a playful tabby kitten with endless curiosity. He loves chasing toys and exploring every corner of the house. Tiger is affectionate and loves being cuddled when he’s tired out from playing. He’s litter trained and ready for his forever home. Tiger would do great in a family with kids or other pets.",
  },
  {
    id: 8,
    name: "Max",
    breed: "Labrador Retriever",
    species: "Dog",
    location: "Cincinnati, OH",
    age: "Adult",
    specialNeeds: false,
    image: "https://placedog.net/300/200?id=4",
    description:
      "Max is a friendly and energetic Labrador Retriever who loves meeting new people. He is loyal and eager to please, making him easy to train. Max enjoys playing fetch and swimming. He would thrive in an active household with plenty of outdoor activities. Max is a great fit for families or individuals seeking a lively companion.",
  },
  {
    id: 9,
    name: "Coco",
    breed: "Parrot",
    species: "Bird",
    location: "Cleveland, OH",
    age: "Old",
    specialNeeds: true,
    image: "https://loremflickr.com/300/200/bird?random=2",
    description:
      "Coco is a charming parrot who loves to mimic sounds and interact with people. Despite needing some extra care, Coco brings a lot of joy with her lively personality. She enjoys sitting on her perch and watching the world around her. Coco is looking for a home with an experienced bird owner.",
  },
  {
    id: 10,
    name: "Oliver",
    breed: "Ragdoll",
    species: "Cat",
    location: "Dayton, OH",
    age: "Young",
    specialNeeds: false,
    image: "https://placekitten.com/300/200?id=4",
    description:
      "Oliver is a stunning Ragdoll cat with a gentle and laid-back personality. He loves being held and will follow you around the house. Oliver enjoys playing with feather toys and lounging in cozy spots. He’s perfect for a family looking for a relaxed and affectionate feline companion.",
  },
  {
    id: 11,
    name: "Bella",
    breed: "Poodle",
    species: "Dog",
    location: "Cleveland, OH",
    age: "Baby",
    specialNeeds: true,
    image: "https://placedog.net/300/200?id=5",
    description:
      "Bella is a bubbly and lovable Poodle who thrives on attention and affection. She’s highly intelligent and quick to learn new commands. Bella enjoys playtime and is always up for an adventure. She would be a perfect fit for a family looking for an engaging and loyal companion.",
  },
  {
    id: 12,
    name: "Chloe",
    breed: "German Shepherd",
    species: "Dog",
    location: "Cincinnati, OH",
    age: "Adult",
    specialNeeds: false,
    image: "https://placedog.net/300/200?id=6",
    description:
      "Chloe is a courageous and intelligent German Shepherd with a protective nature. She loves having a purpose and thrives on training and structure. Chloe enjoys outdoor activities and is loyal to her family. She is looking for a home where she can be both a companion and a protector.",
  },
  {
    id: 13,
    name: "Simba",
    breed: "Labrador Retriever",
    species: "Dog",
    location: "Cleveland, OH",
    age: "Adult",
    specialNeeds: false,
    image: "https://placedog.net/300/200?id=7",
    description:
      "Simba is a Labrador Retriever with an endless supply of love to give. He enjoys long walks and snuggling up after a day of play. Simba is friendly with kids and other pets, making him a great addition to any family. His affectionate personality will brighten anyone's day.",
  },
  {
    id: 14,
    name: "Pumpkin",
    breed: "Tabby",
    species: "Cat",
    location: "Columbus, OH",
    age: "Baby",
    specialNeeds: false,
    image: "https://placekitten.com/300/200?id=8",
    description:
      "Pumpkin is a sweet tabby kitten who is curious about everything. She loves chasing laser pointers and playing with balls of yarn. Pumpkin enjoys cuddling and purring when she’s tired. She would be a delightful addition to any family.",
  },
  {
    id: 15,
    name: "Ruby",
    breed: "Cockatoo",
    species: "Bird",
    location: "Cincinnati, OH",
    age: "Adult",
    specialNeeds: true,
    image: "https://loremflickr.com/300/200/bird?random=3",
    description:
      "Ruby is a stunning cockatoo with a vibrant personality. She loves being around people and enjoys mimicking sounds. Ruby thrives in an environment with plenty of mental stimulation and interaction. She would be perfect for a bird enthusiast.",
  },
  {
    id: 16,
    name: "Rocky",
    breed: "Bulldog",
    species: "Dog",
    location: "Cleveland, OH",
    age: "Young",
    specialNeeds: false,
    image: "https://placedog.net/300/200?id=9",
    description:
      "Rocky is a friendly Bulldog with a big heart. He loves attention and enjoys relaxing with his humans. Rocky is low-maintenance and would be great for a family looking for a calm and loving companion. His goofy personality will keep you smiling every day.",
  },
  {
    id: 17,
    name: "Angel",
    breed: "Himalayan",
    species: "Cat",
    location: "Dayton, OH",
    age: "Old",
    specialNeeds: true,
    image: "https://placekitten.com/300/200?id=9",
    description:
      "Angel is a gentle Himalayan cat with stunning blue eyes. She enjoys quiet afternoons and loves being pampered. Despite needing some special care, Angel is a sweet and affectionate companion who thrives in a calm home environment. She’s ready for a home where she can be spoiled and loved.",
  },
  {
    id: 18,
    name: "Ginger",
    breed: "Dalmatian",
    species: "Dog",
    location: "Columbus, OH",
    age: "Young",
    specialNeeds: false,
    image: "https://placedog.net/300/200?id=10",
    description:
      "Ginger is a lively and energetic Dalmatian who loves playing and going on adventures. She is intelligent and quick to learn new tricks, making her a joy to train. Ginger thrives on affection and enjoys spending time with her human companions. She is looking for an active family who can keep up with her zest for life.",
  },
  {
    id: 19,
    name: "Peanut",
    breed: "Cockapoo",
    species: "Dog",
    location: "Cincinnati, OH",
    age: "Baby",
    specialNeeds: true,
    image: "https://placedog.net/300/200?id=11",
    description:
      "Peanut is an adorable Cockapoo puppy with a playful and loving nature. He enjoys cuddles and chasing after toys. Peanut is eager to learn and would do well with basic training. His cheerful personality makes him an ideal companion for any home.",
  },
  {
    id: 20,
    name: "Milo",
    breed: "Shih Tzu",
    species: "Dog",
    location: "Cleveland, OH",
    age: "Adult",
    specialNeeds: true,
    image: "https://placedog.net/300/200?id=12",
    description:
      "Milo is a sweet and affectionate Shih Tzu who enjoys being close to his humans. Despite needing special care, he is low-maintenance and enjoys quiet moments. Milo loves short walks and cozy afternoons. He’s perfect for someone looking for a small, loving companion.",
  },
  {
    id: 21,
    name: "Snickers",
    breed: "Pug",
    species: "Dog",
    location: "Dayton, OH",
    age: "Young",
    specialNeeds: false,
    image: "https://placedog.net/300/200?id=13",
    description:
      "Snickers is a playful and happy Pug who thrives on attention. He’s great with kids and loves making new friends. Snickers enjoys walks and playing with toys. His adorable face and silly personality make him impossible to resist.",
  },
  {
    id: 22,
    name: "Lilly",
    breed: "Bengal",
    species: "Cat",
    location: "Toledo, OH",
    age: "Adult",
    specialNeeds: false,
    image: "https://placekitten.com/300/200?id=11",
    description:
      "Lilly is an elegant Bengal cat with striking markings. She’s highly intelligent and loves exploring her surroundings. Lilly is affectionate and enjoys interactive toys. She’s ready to bring excitement and companionship to her forever home.",
  },
  {
    id: 23,
    name: "Oscar",
    breed: "Cocker Spaniel",
    species: "Dog",
    location: "Cleveland, OH",
    age: "Old",
    specialNeeds: false,
    image: "https://placedog.net/300/200?id=14",
    description:
      "Oscar is a gentle Cocker Spaniel with a heart of gold. He enjoys leisurely walks and spending time with his humans. Oscar’s calm demeanor makes him an ideal pet for a relaxed home. He’s loyal, loving, and ready to find his forever family.",
  },
  {
    id: 24,
    name: "Peaches",
    breed: "Tabby",
    species: "Cat",
    location: "Columbus, OH",
    age: "Baby",
    specialNeeds: false,
    image: "https://placekitten.com/300/200?id=12",
    description:
      "Peaches is a playful and curious tabby kitten with a love for adventure. She enjoys playing with feather toys and cuddling when she’s sleepy. Peaches is litter-trained and ready to bring joy to her new home.",
  },
  {
    id: 25,
    name: "Duke",
    breed: "Doberman",
    species: "Dog",
    location: "Cincinnati, OH",
    age: "Young",
    specialNeeds: false,
    image: "https://placedog.net/300/200?id=15",
    description:
      "Duke is a strong and intelligent Doberman with a protective nature. He loves being active and thrives on training and structure. Duke is loyal to his family and enjoys outdoor adventures. He’s looking for a home that can match his energy and provide him with plenty of love.",
  },
];
